# -*- coding: utf-8 -*-
"""CS_685_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0Xw_fn1x11e7BgwqMO-Of7z2y8nWbyT

##Dataset Download
The dataset was downloaded from https://irvlab.cs.umn.edu/resources/suim-dataset and then transferred to my google drive
"""

import zipfile
import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')
extract_path = 'suim_dataset'
drive_zip_path = '/content/drive/MyDrive/SUIM.zip'

"""#Dataset Transfer to local Google Colab storage
The dataset is transferred from Google Drive to local Google Colab storage to speed up the retrieval process
"""

import os
import shutil

drive_suim_path = '/content/drive/MyDrive/SUIM'
local_suim_path = '/content/SUIM'

if os.path.exists(drive_suim_path):
    if os.path.exists(local_suim_path):
        shutil.rmtree(local_suim_path)
    print(f"Copying dataset from {drive_suim_path} to local storage")
    shutil.copytree(drive_suim_path, local_suim_path)
    print("Dataset copied to local storage (/content/SUIM)")
else:
    print(f"Folder not found in drive")

"""#Retrieving the Images and corresponding masks from Dataset
This code section goes through the dataset and seperates the raw images from their masks. Further seperates them into training and test image datasets. The training/validation split happens latter
"""

import os
import glob
from sklearn.model_selection import train_test_split

#Finding the pairs of raw images and their corresponding ground truth masks
def get_matched_pairs(root_dir):
    img_files = sorted(glob.glob(os.path.join(root_dir, 'images/*.jpg')))
    mask_files = sorted(glob.glob(os.path.join(root_dir, 'masks/*.*')))
    mask_dict = {os.path.splitext(os.path.basename(m))[0]: m for m in mask_files}
    images = []; masks = []
    for img_p in img_files:
        base = os.path.splitext(os.path.basename(img_p))[0]
        if base in mask_dict:
            images.append(img_p); masks.append(mask_dict[base])
    return images, masks

suim_root = '/content/SUIM'
train_val_root = os.path.join(suim_root, 'train_val')
test_root = os.path.join(suim_root, 'TEST')
train_val_img, train_val_mask = get_matched_pairs(train_val_root)
test_img, test_mask = get_matched_pairs(test_root)

if len(train_val_img) > 0:
    # Re-split
    train_img, val_img, train_mask, val_mask = train_test_split(
        train_val_img, train_val_mask, test_size=0.20, random_state=42
    )
    print(f"Total Training Images: Training images: {len(train_img)}")
else:
    print("Error: No images found in local path")

"""#Preprocessing
Data Augmentation, Image Resizing, Padding, Training/Validation split happens here
"""

import os
import glob
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

#Global constraints for the images
IMG_HEIGHT = 512
IMG_WIDTH = 512
BATCH_SIZE = 8
NUM_CLASSES = 8
IGNORE_LABEL = -1
SHUFFLE_BUFFER = 256

#Converts the raw RGB images into a single channel image with 0-7 indices (one for each class)
def rgb_to_class_indices(mask_rgb):
    mask_binary = tf.cast(mask_rgb > 127, tf.int32)
    r = mask_binary[..., 0]
    g = mask_binary[..., 1]
    b = mask_binary[..., 2]
    class_id = (r * 4) + (g * 2) + b
    return tf.expand_dims(class_id, axis=-1)

#Dataset Split (80% training and 20% validation)
suim_root = '/content/SUIM'
train_val_root = os.path.join(suim_root, 'train_val')
test_root = os.path.join(suim_root, 'TEST')
def get_matched_pairs(root_dir):
    img_files = sorted(glob.glob(os.path.join(root_dir, 'images/*.jpg')))
    mask_files = sorted(glob.glob(os.path.join(root_dir, 'masks/*.*')))
    mask_dict = {os.path.splitext(os.path.basename(m))[0]: m for m in mask_files}
    images = []; masks = []
    for img_p in img_files:
        base = os.path.splitext(os.path.basename(img_p))[0]
        if base in mask_dict:
            images.append(img_p); masks.append(mask_dict[base])
    return images, masks
#Split of the dataset (80/20)
train_val_img, train_val_mask = get_matched_pairs(train_val_root)
test_img, test_mask = get_matched_pairs(test_root)
train_img, val_img, train_mask, val_mask = train_test_split(train_val_img, train_val_mask, test_size=0.20, random_state=42)

#Resizes the images and their masks to the set IMG_HEIGHT and IMG_WIDTH (512x512 for hte final run)
#Ignore label is added here as well, if during resizing it adds padding hten that pixel is labelled as ignore and is not influenced during training
def load_and_preprocess(img_path, mask_path):
    #Raw image
    img = tf.io.read_file(img_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize_with_pad(img, IMG_HEIGHT, IMG_WIDTH)
    #Normalization to 0-1
    img = tf.cast(img, tf.float32) / 255.0
    #Same for mask
    mask = tf.io.read_file(mask_path)
    mask = tf.image.decode_image(mask, channels=3, expand_animations=False)
    mask = rgb_to_class_indices(mask)
    mask = tf.cast(mask, tf.float32) + 1.0
    mask = tf.image.resize_with_pad(mask, IMG_HEIGHT, IMG_WIDTH, method='nearest')
    mask = tf.cast(mask, tf.int32) - 1
    return img, mask
#Data augmentation: randomly scales the image to between 0.75x and 1.25x before resizing to IMG_Height and IMG_width
def random_scale_crop(image, mask):
    scale = tf.random.uniform([], 0.75, 1.25)
    new_h = tf.cast(tf.cast(IMG_HEIGHT, tf.float32) * scale, tf.int32)
    new_w = tf.cast(tf.cast(IMG_WIDTH, tf.float32) * scale, tf.int32)
    image = tf.image.resize(image, [new_h, new_w], method='bilinear')
    mask = tf.image.resize(mask, [new_h, new_w], method='nearest')
    combined = tf.concat([image, tf.cast(mask, tf.float32)], axis=-1)
    combined = tf.image.resize_with_crop_or_pad(combined, IMG_HEIGHT, IMG_WIDTH)
    image = combined[..., :3]
    mask = tf.cast(combined[..., 3:], tf.int32)
    return image, mask
#Additional data augmentation
def augment(image, mask):
    image, mask = random_scale_crop(image, mask)
    #Horizontal Flip (only 50% of images)
    if tf.random.uniform(()) > 0.5:
        image = tf.image.flip_left_right(image)
        mask = tf.image.flip_left_right(mask)
    #Random Birhgtness
    image = tf.image.random_brightness(image, max_delta=0.12)
    #Random conttrast
    image = tf.image.random_contrast(image, lower=0.85, upper=1.15)
    #Random hue
    image = tf.image.random_hue(image, max_delta=0.03)
    #Random saturation
    image = tf.image.random_saturation(image, lower=0.75, upper=1.25)
    #Clipping to ensure pixel values are still valid
    image = tf.clip_by_value(image, 0.0, 1.0)
    return image, mask

#Created tensorflow datasets to increase speed of training
#Caching is done as well to speed up epcohs 2-100
#Initial shuffle is applied to the datasets
#Also groups the images into batches of the hyperparameter BATCH which is 8

#Training tensorflow dataset
train_ds = tf.data.Dataset.from_tensor_slices((train_img, train_mask)) \
    .map(load_and_preprocess, num_parallel_calls=tf.data.AUTOTUNE) \
    .cache() \
    .shuffle(SHUFFLE_BUFFER, reshuffle_each_iteration=True) \
    .map(augment, num_parallel_calls=tf.data.AUTOTUNE) \
    .batch(BATCH_SIZE) \
    .prefetch(tf.data.AUTOTUNE)
#Validation tensorflow dataset
val_ds = tf.data.Dataset.from_tensor_slices((val_img, val_mask)) \
    .map(load_and_preprocess, num_parallel_calls=tf.data.AUTOTUNE) \
    .cache().batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
#Test tensorflow dataset
test_ds = tf.data.Dataset.from_tensor_slices((test_img, test_mask)) \
    .map(load_and_preprocess, num_parallel_calls=tf.data.AUTOTUNE) \
    .cache().batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

"""#GPU Check
Checking to determine that the GPU is being used for this notebook. It is recommended that at least the A100 GPU is used as the free GPU will run out of RAM before finishing the first Epoch. Also, if a GPU is being used then mixed precision is used to increase perfomance
"""

import tensorflow as tf
# Check if GPU is available
gpu_devices = tf.config.list_physical_devices('GPU')
if gpu_devices:
    print(f"GPU found: {gpu_devices[0]}")
    # Enable mixed precision for faster training
    from tensorflow.keras import mixed_precision
    policy = mixed_precision.Policy('mixed_float16')
    mixed_precision.set_global_policy(policy)
    print("Mixed precision enabled")
else:
    print("No GPU found")

"""#Data split
This cell shows the number of images for training, val, and test sets
"""

print(f"Number of Training images: {len(train_img)}")
print(f"Number of Validation images: {len(val_img)}")
print(f"Number of Test images: {len(test_img)}")
total_images = len(train_img) + len(val_img) + len(test_img)
print(f"Total images: {total_images}")

"""#U-Net Implementation
This code block is the archetecture for the U-Net implemented in this project. Hyperparameters are set at the top of the code block and the model is built in the rest of the code block. See additional comments for each section of the model.
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import tensorflow.keras.backend as K
import numpy as np

#Hyperparameters
NUM_FILTERS = 32
DROPOUT_RATE = 0.2
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-4
OUTPUT_CHANNELS = 8

#Class weights for weighted loss, these were chosen by looking at the pixel class distribution
class_weights = np.array([1.0, 5.0, 10.0, 5.0, 15.0, 2.0, 5.0, 2.0], dtype=np.float32)
raw_weights = tf.cast(class_weights, tf.float32)
stable_class_weights = tf.where(tf.math.is_finite(raw_weights), raw_weights + 1e-6, 1.0)

#This function calculates accuracy while ignoring the pixels that were labelled ignore (padded pixels)
class MaskedSparseCategoricalAccuracy(tf.keras.metrics.Metric):
    def __init__(self, name="pixel_accuracy", **kwargs):
        super().__init__(name=name, **kwargs)
        self.correct = self.add_weight(name="correct", initializer="zeros")
        self.total = self.add_weight(name="total", initializer="zeros")

    def update_state(self, y_true, y_pred, sample_weight=None):
        y_true = tf.cast(tf.squeeze(y_true, axis=-1), tf.int32)
        y_pred = tf.argmax(y_pred, axis=-1, output_type=tf.int32)
        valid = tf.not_equal(y_true, -1)
        matches = tf.equal(y_true, y_pred)
        matches = tf.cast(tf.logical_and(matches, valid), tf.float32)
        valid = tf.cast(valid, tf.float32)
        self.correct.assign_add(tf.reduce_sum(matches))
        self.total.assign_add(tf.reduce_sum(valid))

    def result(self):
        return self.correct / (self.total + 1e-7)

    def reset_state(self):
        self.correct.assign(0.0)
        self.total.assign(0.0)

#Calculates the IOU and filters out background or ignore labelled pixels
class SparseMeanIoU(tf.keras.metrics.MeanIoU):
    def __init__(self, num_classes, name='total_mean_iou', dtype=None):
        super(SparseMeanIoU, self).__init__(num_classes=num_classes, name=name, dtype=dtype)
    def update_state(self, y_true, y_pred, sample_weight=None):
        y_true = tf.cast(y_true, tf.int32)
        y_true_squeezed = tf.squeeze(y_true, axis=-1)
        mask = tf.not_equal(y_true_squeezed, -1)
        y_true_masked = tf.boolean_mask(y_true_squeezed, mask)
        y_pred_indices = tf.argmax(y_pred, axis=-1)
        y_pred_masked = tf.boolean_mask(y_pred_indices, mask)
        return super().update_state(y_true_masked, y_pred_masked, sample_weight)

#WSCC Loss, part 1 of the hybrid loss for the model
def weighted_sparse_categorical_crossentropy(weights):
    def loss(y_true, y_pred):
        y_true = tf.cast(y_true, tf.int32)
        y_true = tf.squeeze(y_true, axis=-1)
        valid = tf.cast(tf.not_equal(y_true, -1), tf.float32)
        y_true_safe = tf.where(y_true == -1, 0, y_true)
        pixel_losses = tf.keras.losses.sparse_categorical_crossentropy(y_true_safe, y_pred)
        weight_mask = tf.gather(weights, y_true_safe)
        weight_mask = weight_mask * valid
        return tf.reduce_sum(pixel_losses * weight_mask) / (tf.reduce_sum(weight_mask) + 1e-7)
    return loss

#Dice Loss, part 2 of the hybrid loss for the model
def dice_loss(y_true, y_pred):
    y_true = tf.cast(y_true, tf.int32)
    valid_mask = tf.cast(tf.not_equal(y_true, -1), tf.float32)
    y_true_oh = tf.one_hot(tf.squeeze(y_true, -1), OUTPUT_CHANNELS)
    y_true_oh = tf.cast(y_true_oh, tf.float32)
    y_true_oh = y_true_oh * valid_mask
    y_pred = y_pred * valid_mask
    smooth = 1e-6
    intersection = tf.reduce_sum(y_true_oh * y_pred, axis=(1, 2))
    sum_true = tf.reduce_sum(y_true_oh, axis=(1, 2))
    sum_pred = tf.reduce_sum(y_pred, axis=(1, 2))
    dice = (2. * intersection + smooth) / (sum_true + sum_pred + smooth)
    presence_mask = tf.cast(tf.reduce_sum(y_true_oh, axis=(1, 2)) > 0, tf.float32)
    dice_present = (dice * presence_mask)
    dice_loss_val = 1.0 - (tf.reduce_sum(dice_present, axis=-1) / (tf.reduce_sum(presence_mask, axis=-1) + smooth))
    return tf.reduce_mean(dice_loss_val)

#Combines WSCC Loss and Dice Loss to generate hybrid loss
def hybrid_loss(weights):
    ce_loss_fn = weighted_sparse_categorical_crossentropy(weights)
    def loss(y_true, y_pred):
        return ce_loss_fn(y_true, y_pred) + dice_loss(y_true, y_pred)
    return loss

#Convolutional Block
#Comprised of 2 3x3 convolutions, batch normalization after each convolution. Dropout is only done on the deepest encoder layers
def conv_block(inputs, filters, dropout_rate):
    c = layers.Conv2D(filters, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(inputs)
    c = layers.BatchNormalization()(c)
    c = layers.Conv2D(filters, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c)
    c = layers.BatchNormalization()(c)
    if dropout_rate > 0:
        c = layers.SpatialDropout2D(dropout_rate)(c)
    return c

#Upsamling layers used in the decoder section
def upsample_conv(inputs, filters):
    u = layers.UpSampling2D((2, 2), interpolation='bilinear')(inputs)
    u = layers.Conv2D(filters, 3, padding='same', activation='relu')(u)
    return u

#U-Net architecture
#5 Encoder blocks, the first four are followed by 2x2 max pooling for downsampling, the last encoder block acts as a bottleneck
#For each encoder block the number of filters doubled till it gets to filters*16 which is 512 at the bottleneck
#4 Decoder blocks, each one upsamples and then concatenates with the downsampling layer to attempt to recapture any lost features
def unet_model(input_size=(512, 512, 3)):
    inputs = layers.Input(input_size)
    #Encoder/Downsampling
    c1 = conv_block(inputs, NUM_FILTERS, 0)
    p1 = layers.MaxPooling2D((2, 2))(c1)
    c2 = conv_block(p1, NUM_FILTERS * 2, 0)
    p2 = layers.MaxPooling2D((2, 2))(c2)
    c3 = conv_block(p2, NUM_FILTERS * 4, DROPOUT_RATE)
    p3 = layers.MaxPooling2D((2, 2))(c3)
    c4 = conv_block(p3, NUM_FILTERS * 8, DROPOUT_RATE)
    p4 = layers.MaxPooling2D((2, 2))(c4)
    #Bottleneck
    c5 = conv_block(p4, NUM_FILTERS * 16, DROPOUT_RATE)
    #Decoder/Upsampling
    u6 = upsample_conv(c5, NUM_FILTERS * 8)
    u6 = layers.concatenate([u6, c4])
    c6 = conv_block(u6, NUM_FILTERS * 8, 0)
    u7 = upsample_conv(c6, NUM_FILTERS * 4)
    u7 = layers.concatenate([u7, c3])
    c7 = conv_block(u7, NUM_FILTERS * 4, 0)
    u8 = upsample_conv(c7, NUM_FILTERS * 2)
    u8 = layers.concatenate([u8, c2])
    c8 = conv_block(u8, NUM_FILTERS * 2, 0)
    u9 = upsample_conv(c8, NUM_FILTERS)
    u9 = layers.concatenate([u9, c1])
    c9 = conv_block(u9, NUM_FILTERS, 0)
    #Output has 8 channels to label each pixel to 8 classes
    outputs = layers.Conv2D(OUTPUT_CHANNELS, (1, 1), activation='softmax', dtype='float32')(c9)
    return models.Model(inputs=[inputs], outputs=[outputs])

#Using AdamW as the optimized
model = unet_model()
model.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=LEARNING_RATE, weight_decay=WEIGHT_DECAY, clipnorm=1.0),
    loss=hybrid_loss(stable_class_weights),
    metrics=[
        MaskedSparseCategoricalAccuracy(),
        SparseMeanIoU(num_classes=OUTPUT_CHANNELS)
    ]
)

"""#Model Saving, Training Model"""

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras import mixed_precision
import shutil
import os

#Have to set this policy here otherwise there will be errors
mixed_precision.set_global_policy('float32')

#Recompiling the model with the global policy
model = unet_model()
model.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=LEARNING_RATE, weight_decay=WEIGHT_DECAY, clipnorm=1.0),
    loss=hybrid_loss(stable_class_weights),
    metrics=[
        MaskedSparseCategoricalAccuracy(),
        SparseMeanIoU(num_classes=OUTPUT_CHANNELS)
    ]
)

#This is where the model will be saved
local_model_path = '/content/SUIM_best_model.keras'
drive_model_path = '/content/drive/MyDrive/SUIM_best_model.keras'

#Saving the model after each epoch so it doesn't lose progress in case it gets disconnected
#Also, early stopping if the validation mean IOU does not improve over X epochs
#Also halves learning rate if validation mean IOU does not imrpvoe over 5 epochs

callbacks = [
    ModelCheckpoint(
        local_model_path,
        monitor='val_total_mean_iou',
        mode='max',
        verbose=1,
        save_best_only=True
    ),
    EarlyStopping(monitor='val_total_mean_iou', mode='max', patience=10, restore_best_weights=True),
    ReduceLROnPlateau(
        monitor='val_total_mean_iou',
        mode='max',
        factor=0.5,
        patience=5,
        min_lr=1e-7,
        verbose=1
    )
]
#Setting epochs to 100, have tested with 50 and 75 epochs. 100 seems to be the best. Might want to try 125 epochs as well
EPOCHS = 100
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=callbacks,
    verbose=1
)

#Copying the best model to Drive after training finishes so it doesn't have to be trained each time
if os.path.exists(local_model_path):
    shutil.copy(local_model_path, drive_model_path)
    print(f"Best model copied to Drive at: {drive_model_path}")

"""#Plotting of the Training and Validation Loss, Accuracy, Mean IOU

"""

import matplotlib.pyplot as plt

def plot_training_history(history):
    #Three plots, left->right: accuracy, hybrid loss, mean IOU
    acc = history.history['pixel_accuracy']
    val_acc = history.history['val_pixel_accuracy']
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    iou_key = next((k for k in history.history.keys() if 'iou' in k and 'val' not in k), None)
    val_iou_key = next((k for k in history.history.keys() if 'iou' in k and 'val' in k), None)
    epochs_range = range(len(acc))
    #Accuracy plot
    plt.figure(figsize=(18, 6))
    plt.subplot(1, 3, 1)
    plt.plot(epochs_range, acc, label='Training Pixel Accuracy')
    plt.plot(epochs_range, val_acc, label='Validation Pixel Accuracy')
    plt.xlabel('Epoch Number')
    plt.ylabel('Pixel Accuracy')
    plt.legend(loc='best')
    plt.title('Pixel Accuracy')
    plt.grid(True, linestyle='--', alpha=0.6)
    #Hybrid Loss Plot
    plt.subplot(1, 3, 2)
    plt.plot(epochs_range, loss, label='Training Loss')
    plt.plot(epochs_range, val_loss, label='Validation Loss')
    plt.xlabel('Epoch Number')
    plt.ylabel('Weighted Sparse Categorical Crossentropy')
    plt.legend(loc='best')
    plt.title('Hybrid Loss (Weighted Sparse Categorical Crossentropy Loss + Dice Loss)')
    plt.grid(True, linestyle='--', alpha=0.6)
    #Mean IOU Plot
    if iou_key and val_iou_key:
        plt.subplot(1, 3, 3)
        plt.plot(epochs_range, history.history[iou_key], label='Training Mean IoU')
        plt.plot(epochs_range, history.history[val_iou_key], label='Validation Mean IoU')
        plt.xlabel('Epoch Number')
        plt.ylabel('Mean IoU')
        plt.legend(loc='best')
        plt.title('Mean IoU')
        plt.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.show()

if 'history' in globals():
    plot_training_history(history)
else:
    print("No model history")

"""#Validation visualizations
foreground mean IOU is better to compare than the total mean IOU. Plotting a sample of ten validation images
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

#Loading the model if it is not in local
drive_model_path = '/content/drive/MyDrive/SUIM_best_model.keras'
if 'model' not in globals():
    if os.path.exists(drive_model_path):
        print(f"Loading model from {drive_model_path}...")
        model = tf.keras.models.load_model(drive_model_path, compile=False)
    else:
        print("Model file not found. Ensure training finished and Drive is mounted.")

#Calculating the mean IOU for the five foreground classes
def calculate_foreground_iou(y_true, y_pred):
    y_true = tf.cast(y_true, tf.int32).numpy().flatten()
    y_pred = y_pred.flatten()
    # Focus on non-background (class > 0)
    intersection = np.logical_and(y_true == y_pred, y_true > 0).sum()
    union = np.logical_or(y_true > 0, y_pred > 0).sum()
    return intersection / (union + 1e-6)

#Plotting ten images with their ground truth and prediction from the model
def plot_first_validation_samples(dataset, model, num_samples=10):
    count = 0
    for images, masks in dataset:
        if count >= num_samples:
            break
        #Segmentation Prediction
        preds = model.predict(images, verbose=0)
        preds_t = np.argmax(preds, axis=-1)
        for i in range(len(images)):
            if count >= num_samples:
                break
            img = images[i].numpy()
            mask = masks[i].numpy()
            pred = preds_t[i]
            iou_score = calculate_foreground_iou(mask, pred)
            fig, axes = plt.subplots(3, 1, figsize=(6, 10))
            #Each plot will be 3 images, row 1 will be the raw image, row 2 is ground truth, row 3 is predicted mask
            plt.subplots_adjust(hspace=0.3)
            axes[0].imshow(img)
            axes[0].set_title(f"Sample {count+1} - Input")
            axes[0].axis('off')
            axes[1].imshow(mask.squeeze(), cmap='jet', vmin=0, vmax=7)
            axes[1].set_title("Ground Truth")
            axes[1].axis('off')
            axes[2].imshow(pred, cmap='jet', vmin=0, vmax=7)
            axes[2].set_title(f"Prediction (Foreground IoU: {iou_score:.4f})")
            axes[2].axis('off')
            plt.show()
            count += 1

if 'val_ds' in globals() and 'model' in globals():
    plot_first_validation_samples(val_ds, model, num_samples=10)
else:
    print("Error")

"""#Mean IOU
Calculates the mean IOU for training, validation, and test datasets. Generates a table showing total mean IOU across all classes and then also mean IOU for each specific class
"""

import pandas as pd
import numpy as np
import tensorflow as tf
import os

def evaluate_and_table(dataset, model, dataset_name="Test"):
    #Labelling the eight classes
    class_names = [
        'Background', 'Human diver', 'Aquatic plants', 'Wrecks/Ruins',
        'Robots/Instruments', 'Reefs', 'Fish', 'Sea-floor'
    ]
    print(f"Evaluating model on {dataset_name} dataset, this will take several minutes")
    num_classes = len(class_names)
    total_cm = np.zeros((num_classes, num_classes))
    #Goes through each image, generates prediction masks for each class and generates a confusion matrix
    for images, masks in dataset:
        preds = model.predict(images, verbose=0)
        preds_indices = np.argmax(preds, axis=-1).flatten()
        masks_indices = tf.cast(masks, tf.int32).numpy().flatten()
        valid_mask = masks_indices != -1 #The model is not punished for pixels that have the ignore label
        v_masks = masks_indices[valid_mask]
        v_preds = preds_indices[valid_mask]
        if len(v_masks) > 0:
            indices = v_masks * num_classes + v_preds
            m = np.bincount(indices, minlength=num_classes**2).reshape(num_classes, num_classes)
            total_cm += m
    #Calculates the mean IOU
    intersection = np.diag(total_cm)
    ground_truth_set = total_cm.sum(axis=1)
    predicted_set = total_cm.sum(axis=0)
    union = ground_truth_set + predicted_set - intersection
    #Seperates IOU per class
    iou_per_class = np.divide(intersection, union, out=np.zeros_like(intersection), where=union != 0)
    acc_per_class = np.divide(intersection, ground_truth_set, out=np.zeros_like(intersection), where=ground_truth_set != 0)
    manual_pixel_acc = np.sum(intersection) / (np.sum(total_cm) + 1e-7)
    #prints results
    print(f"\n{dataset_name} Results:")
    print(f"Manual Mean IoU: {np.mean(iou_per_class):.4f}")
    print(f"Manual Global Pixel Accuracy: {manual_pixel_acc:.4f}")
    print("Ground-truth class distribution (pixels):", ground_truth_set)
    print("Predicted class distribution (pixels):   ", predicted_set)
    df_metrics = pd.DataFrame({
        'Class': class_names,
        'IoU': iou_per_class,
        'Pixel Accuracy (Recall)': acc_per_class
    })
    display(df_metrics)
    print("-" * 30)

drive_model_path = '/content/drive/MyDrive/SUIM_best_model.keras'
if 'model' not in globals():
    if os.path.exists(drive_model_path):
        model = tf.keras.models.load_model(drive_model_path, compile=False)

required_datasets = ['train_ds', 'val_ds', 'test_ds']
missing = [ds for ds in required_datasets if ds not in globals()]

if missing:
    print(f"Missing: {missing}")
elif 'model' in globals():
    evaluate_and_table(train_ds, model, "Training")
    evaluate_and_table(val_ds, model, "Validation")
    evaluate_and_table(test_ds, model, "Test")

"""#Visualization on Test Data Set
Random 3 images from the test data set
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import random

#Loading the model in through google drive or if in local memory
drive_model_path = '/content/drive/MyDrive/SUIM_best_model.keras'
if 'model' not in globals():
    if os.path.exists(drive_model_path):
        model = tf.keras.models.load_model(drive_model_path, compile=False)

#Calculates foregound IOU, used in the plot title
def calculate_foreground_iou(y_true, y_pred):
    y_true = tf.cast(y_true, tf.int32).numpy().flatten()
    y_pred = y_pred.flatten()
    intersection = np.logical_and(y_true == y_pred, y_true > 0).sum()
    union = np.logical_or(y_true > 0, y_pred > 0).sum()
    return intersection / (union + 1e-6)

def visualize_random_samples(dataset, model, image_paths, num_samples=3):
    class_names = [
        'Background', 'Human diver', 'Aquatic plants', 'Wrecks/Ruins',
        'Robots/Instruments', 'Reefs', 'Fish', 'Sea-floor'
    ]
    total_test = len(image_paths)
    start_idx = random.randint(0, max(0, total_test - num_samples))
    random_batch = dataset.unbatch().skip(start_idx).batch(num_samples).take(1)
    for images, masks in random_batch:
        #Prediction masks
        preds = model.predict(images, verbose=0)
        preds_t = np.argmax(preds, axis=-1)
        num_to_show = min(num_samples, len(images))
        plt.figure(figsize=(22, num_to_show * 4))
        #The plot will be number of sample rows x 3 columns
        #The far left image will be the raw image, middle will be hte ground truth, and the far right image will be the prediction mask
        for i in range(num_to_show):
            img = images[i].numpy()
            mask = masks[i].numpy()
            pred = preds_t[i]
            iou_score = calculate_foreground_iou(mask, pred)
            img_filename = os.path.basename(image_paths[start_idx + i])
            #Image 1
            plt.subplot(num_to_show, 4, 4*i + 1)
            plt.imshow(img)
            plt.title(f"Test Image: {img_filename}")
            plt.axis('off')
            #Image 2
            plt.subplot(num_to_show, 4, 4*i + 2)
            plt.imshow(tf.squeeze(mask), cmap='jet', vmin=0, vmax=7)
            plt.title("Ground Truth")
            plt.axis('off')
            #Image 3
            plt.subplot(num_to_show, 4, 4*i + 3)
            plt.imshow(pred, cmap='jet', vmin=0, vmax=7)
            plt.title(f"Prediction (Foreground IoU: {iou_score:.4f})")
            plt.axis('off')
            #Full Plot
            ax_legend = plt.subplot(num_to_show, 4, 4*i + 4)
            if i == 0:
                for class_idx in range(len(class_names)):
                    color = plt.cm.jet(class_idx / (len(class_names) - 1))
                    ax_legend.plot(0, 0, 's', color=color, label=class_names[class_idx], markersize=10)
                ax_legend.legend(loc='center', title="Classes")
                ax_legend.set_title("Color Legend")
            ax_legend.axis('off')
        plt.tight_layout()
        plt.show()

if 'test_ds' in globals() and 'model' in globals() and 'test_img' in globals():
    visualize_random_samples(test_ds, model, test_img, num_samples=3)
else:
    print("Error b")